[project]
name = "cat-experiment-pyglet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyglet>=2.1.3",
    "pyinstaller>=6.12.0",
]
